/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:11c98eb6-b204-450a-a00c-df9f38e662db",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UVvumYK1b",
    "aws_user_pools_web_client_id": "7ao0b4oi59cfhetp41fskki1ae",
    "oauth": {}
};


export default awsmobile;
